{
  "formatVersion": "1.1",
  "component": {
    "group": "de.keksuccino",
    "module": "mcef-neoforge",
    "version": "2.1.7-1.21.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "mcef-neoforge-2.1.7-1.21.6.jar",
          "url": "mcef-neoforge-2.1.7-1.21.6.jar",
          "size": 220401,
          "sha512": "5c24e91add7246918cb6fcca80c97f4eed0fe451636dec7f288fa7736f7eecf8fc16ade3cf39a227df60029700e8c86f24fcb9cebb8f9b9a26d6d22a7b5ceb70",
          "sha256": "2328c9ce1c175b829684eb5fe510308d30fba9580c7c11a2581391a9ee0b314c",
          "sha1": "5479a429b69e33223f120b5063979a824c53c6a1",
          "md5": "60e4c9ccb79513efdc35e1ca5d721c4f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "de.keksuccino",
          "module": "mcef",
          "version": {
            "requires": "2.1.7-1.21.6"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "mcef-neoforge-2.1.7-1.21.6.jar",
          "url": "mcef-neoforge-2.1.7-1.21.6.jar",
          "size": 220401,
          "sha512": "5c24e91add7246918cb6fcca80c97f4eed0fe451636dec7f288fa7736f7eecf8fc16ade3cf39a227df60029700e8c86f24fcb9cebb8f9b9a26d6d22a7b5ceb70",
          "sha256": "2328c9ce1c175b829684eb5fe510308d30fba9580c7c11a2581391a9ee0b314c",
          "sha1": "5479a429b69e33223f120b5063979a824c53c6a1",
          "md5": "60e4c9ccb79513efdc35e1ca5d721c4f"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "mcef-neoforge-2.1.7-1.21.6.jar",
          "url": "mcef-neoforge-2.1.7-1.21.6.jar",
          "size": 220401,
          "sha512": "0dd6562bd501dd69f3e931b6fcc575c4216188c5469b04e81bb1bebdc93df835c645b1ee3cfb6dda25d98375e584f044f4a4a47eaefbc0ae61a989b2ddead604",
          "sha256": "7a03fb71209b459a4da6ed50e0369eb3d5fef6a2a9f6d93b4ed2670ef577a2e2",
          "sha1": "bbf8d59a9fbf9b5c8bf91e257d1e91b5fa98e035",
          "md5": "fd45aa18aa749d0181298a98ff6393d7"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "mcef-neoforge-2.1.7-1.21.6-sources.jar",
          "url": "mcef-neoforge-2.1.7-1.21.6-sources.jar",
          "size": 184349,
          "sha512": "a6c8c777eb9b3c58b3a7db94c2f60a0cfc338bc03bc425017ab9281cfd98cac406d6acdbbaf69989e76559c8fc39bf13f62b88ac5a5cc6ce6efc40bcec5b6e51",
          "sha256": "3fb154a64f73e80643763a95a2fd7e60b8cd15d3d0c5f13f05276fac920eb836",
          "sha1": "890821b250144ace5f367188e6184d0728c8f2bf",
          "md5": "691dbf4ccaa978cfe920ecdb7bf9ab86"
        }
      ]
    }
  ]
}
