{
  "formatVersion": "1.1",
  "component": {
    "group": "de.keksuccino",
    "module": "mcef-fabric",
    "version": "2.1.7-1.21.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "mcef-fabric-2.1.7-1.21.6.jar",
          "url": "mcef-fabric-2.1.7-1.21.6.jar",
          "size": 227057,
          "sha512": "3825911998e5dbb592777712ef4f0ae30f294db7ad1355c639ba23718232ff31b9c19929ac9de892ac784cd7ad8aa0840aefcc8936c3784a457e76d2fceacb4a",
          "sha256": "415a4f8207ce41136054fbf8bf0ef61dfa2d1edfae30233af4dda940b6ae7e2e",
          "sha1": "45644a69b2a0e04be2d841ca8bcd17371f64d760",
          "md5": "9675fac3ae1e4c689d8db07922f9c70a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "de.keksuccino",
          "module": "mcef",
          "version": {
            "requires": "2.1.7-1.21.6"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.17.3"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api-base",
          "version": {
            "requires": "0.4.64+9ec45cd896"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-command-api-v2",
          "version": {
            "requires": "2.2.53+946bf4c396"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-lifecycle-events-v1",
          "version": {
            "requires": "2.6.3+db4dfd8596"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-networking-api-v1",
          "version": {
            "requires": "5.0.1+946bf4c396"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-resource-loader-v0",
          "version": {
            "requires": "3.1.11+946bf4c396"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-key-binding-api-v1",
          "version": {
            "requires": "1.0.65+946bf4c396"
          }
        }
      ],
      "files": [
        {
          "name": "mcef-fabric-2.1.7-1.21.6.jar",
          "url": "mcef-fabric-2.1.7-1.21.6.jar",
          "size": 227057,
          "sha512": "3825911998e5dbb592777712ef4f0ae30f294db7ad1355c639ba23718232ff31b9c19929ac9de892ac784cd7ad8aa0840aefcc8936c3784a457e76d2fceacb4a",
          "sha256": "415a4f8207ce41136054fbf8bf0ef61dfa2d1edfae30233af4dda940b6ae7e2e",
          "sha1": "45644a69b2a0e04be2d841ca8bcd17371f64d760",
          "md5": "9675fac3ae1e4c689d8db07922f9c70a"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "mcef-fabric-2.1.7-1.21.6-shadow-dev.jar",
          "url": "mcef-fabric-2.1.7-1.21.6-shadow-dev.jar",
          "size": 220555,
          "sha512": "ab8182933c7530f45543e20af1adb49c68216c4baf1d24936c8fdcd76fc0d0d4d81f577e612efd1185b552780ba206fa38145dc810f3b9ddb6d167f8b4c24ecf",
          "sha256": "737152a90b4f89fa6cff7cef27dcf5e42d223616c8905fd70b3a81fdedc51584",
          "sha1": "7a859c66ce4191a6b8b6bb51a20aefc6b8d79b3b",
          "md5": "6ab20bd82a85b0c391d3ad8ef68eed62"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "mcef-fabric-2.1.7-1.21.6-sources.jar",
          "url": "mcef-fabric-2.1.7-1.21.6-sources.jar",
          "size": 198043,
          "sha512": "864129788af94303a1821e1e4d9c259ddf61858ba964f338dc905763ce5fe52d57bdbc1d6aee4673c2beae5ab40773b27d35e475317b53d8547d2e3fdb657c31",
          "sha256": "4320c3734e897b5c072f1fe15589534cf4b66d4e78e52ff996410627c961b717",
          "sha1": "73e81b8a15fe5245936a557cd092241c3b8a94ca",
          "md5": "cbdbc9a98fc34ed586d3acaf1824eadb"
        }
      ]
    }
  ]
}
