{
  "formatVersion": "1.1",
  "component": {
    "group": "de.keksuccino",
    "module": "mcef-fabric",
    "version": "2.1.7-1.21.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "mcef-fabric-2.1.7-1.21.6.jar",
          "url": "mcef-fabric-2.1.7-1.21.6.jar",
          "size": 227056,
          "sha512": "14708bffde4d7fec6088e7814cd84c8742d43f0f17dc4cabc01aeb7c6026111d90196d0406410b3b7e9091885730b227a3a49a9b82836281045f26f7677fc0fe",
          "sha256": "3e47aa049365c1f9dd586c895bf243abd707be032d60f7719765e2f551b999e2",
          "sha1": "fe282b9cea1128c796a7ae89f584253f547421dd",
          "md5": "725659de2712b4798d8e09b395f37718"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.cinemamod",
          "module": "mcef",
          "version": {
            "requires": "2.1.7-1.21.6"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.17.3"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api-base",
          "version": {
            "requires": "0.4.64+9ec45cd896"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-command-api-v2",
          "version": {
            "requires": "2.2.53+946bf4c396"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-lifecycle-events-v1",
          "version": {
            "requires": "2.6.3+db4dfd8596"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-networking-api-v1",
          "version": {
            "requires": "5.0.1+946bf4c396"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-resource-loader-v0",
          "version": {
            "requires": "3.1.11+946bf4c396"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-key-binding-api-v1",
          "version": {
            "requires": "1.0.65+946bf4c396"
          }
        }
      ],
      "files": [
        {
          "name": "mcef-fabric-2.1.7-1.21.6.jar",
          "url": "mcef-fabric-2.1.7-1.21.6.jar",
          "size": 227056,
          "sha512": "14708bffde4d7fec6088e7814cd84c8742d43f0f17dc4cabc01aeb7c6026111d90196d0406410b3b7e9091885730b227a3a49a9b82836281045f26f7677fc0fe",
          "sha256": "3e47aa049365c1f9dd586c895bf243abd707be032d60f7719765e2f551b999e2",
          "sha1": "fe282b9cea1128c796a7ae89f584253f547421dd",
          "md5": "725659de2712b4798d8e09b395f37718"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "mcef-fabric-2.1.7-1.21.6-shadow-dev.jar",
          "url": "mcef-fabric-2.1.7-1.21.6-shadow-dev.jar",
          "size": 220555,
          "sha512": "358e71add09a05f4c5711a90cba8e83a98b2a1e034fca39ac3fbc9960a09599dee703c736381d22a4eacbf3c8deb9b92a17726c5c97b30eeec4bacb92e1c8a50",
          "sha256": "8e27b25f508cf2544afa0bd0c4ff7f13de3090b33e4f5bcc4b00b1c20eb2670e",
          "sha1": "9c102cab541f4b0cfc6f2209ebde65e1d6aa9d25",
          "md5": "a06a20c0cf8b6665c9d39fa953cad347"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "mcef-fabric-2.1.7-1.21.6-sources.jar",
          "url": "mcef-fabric-2.1.7-1.21.6-sources.jar",
          "size": 198043,
          "sha512": "691b4b988c4bda3a5141b543d2e7d09c6917abedbc2d32df29d89847ba5a918e59da482787be83bc57c80d855bd19801095d7e8f346030ec1b6bd7cf95cd26b0",
          "sha256": "de3ed17bb6022c2ee7599183e353e62d1ed6fff89c96c5c693c91cdda7dede10",
          "sha1": "7418823a9ca8e753e997bc934b657ef3a9b7c8c8",
          "md5": "3ad61cd0ff3e3613ce57b0b00433d191"
        }
      ]
    }
  ]
}
