{
  "formatVersion": "1.1",
  "component": {
    "group": "de.keksuccino",
    "module": "rinku-neoforge",
    "version": "3.0.2-1.21.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "rinku-neoforge-3.0.2-1.21.1.jar",
          "url": "rinku-neoforge-3.0.2-1.21.1.jar",
          "size": 615828,
          "sha512": "d9dd0d112cc703d678d9ac50b4ef28e770910ec7c3ed9a652a7e23c46cfd9ea4523555e49010bf3f05ea4be9ec3121ee5995f260d0b2f62da20a4876d01e4966",
          "sha256": "e0f87aeda69d74215daa16fe900208d0e0edfe7812b5fce01bf12db36d7b42c5",
          "sha1": "3483df402c70f1e09536f1bb1514a137a4724440",
          "md5": "9ea917b5f977989e03fc1956e1d43a89"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "rinku-neoforge-3.0.2-1.21.1.jar",
          "url": "rinku-neoforge-3.0.2-1.21.1.jar",
          "size": 615828,
          "sha512": "d9dd0d112cc703d678d9ac50b4ef28e770910ec7c3ed9a652a7e23c46cfd9ea4523555e49010bf3f05ea4be9ec3121ee5995f260d0b2f62da20a4876d01e4966",
          "sha256": "e0f87aeda69d74215daa16fe900208d0e0edfe7812b5fce01bf12db36d7b42c5",
          "sha1": "3483df402c70f1e09536f1bb1514a137a4724440",
          "md5": "9ea917b5f977989e03fc1956e1d43a89"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "rinku-neoforge-3.0.2-1.21.1-sources.jar",
          "url": "rinku-neoforge-3.0.2-1.21.1-sources.jar",
          "size": 418569,
          "sha512": "cd08e330589eb8ec39f188b43f8ab043b606b5b7a81a6495235f28da16d8a30fb93c9391509405db49e5d14470519e11cb658af5ad84035ca271a6f15313ad04",
          "sha256": "ad3bdc3eeef4f66c3c8f31831fdd7798102764ba14e477dcef5ad57891184ac8",
          "sha1": "4625e704c09d0b6e285b75949b000f3c72c9a4c0",
          "md5": "a4c0dcd437617139be1fe4770c71420a"
        }
      ]
    }
  ]
}
